### ISSUE TITLE
Support formatting shortcuts

### ISSUE THREAD

**Issue by surya-sk** [morning4coffe-dev/storylines#22]
Hey! I really love this app. The only thing that is kind of bugging me is how there is no support for formatting shortcuts, like Ctrl +B for Bold and so on, like in most other text editors. It would be nice to have this feature. If I've got some time, I'll put in a pull request, but no promises there.

**Comment by morning4coffe-dev** [comment]
@surya-sk Hi. Thank you for your kind words! 

Hmm... are you using the most recent version? 🤔 Pressing `Ctrl+Shift+B` when having some text selected should work. If you want to check other shortcuts, you can find them in Help > Keyboard shortcuts. 

If you're interested in contributing, I would be more than happy to assist you in any way. Personally, for me Storylines has not been a priority recently as I am working on different projects, but I still have plans to make bigger updates in the future after I finalize the most requested feature - multiplatform, which has been quite the challenge.

**Comment by surya-sk** [comment]
Hey thanks for your response. For some reason the Store didn't automatically update the app, I did it manually and it works now. My bad! 

Also just curious, do you plan on using Uno platform to get it on other platforms or just use a native stack? Either way, it is a challenge aha, I can attest to that.

**Comment by morning4coffe-dev** [comment]
-> discussions https://github.com/morning4coffe-dev/storylines/discussions/23
